apiVersion: v1
kind: Secret
metadata:
  name: central-auth-secrets
  namespace: note-app
type: Opaque
data:
  JWT_SECRET: "YzY2ODJmYTcwZTk4NTEzMGMxYjM0MmVhM2VjZjc5ZjVhMzczZjU2MmEzZmNkZDIxMTJmZTI0YmY1NGQ3NTE3Yw=="