apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-go
  namespace: note-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note-go
  template:
    metadata:
      labels:
        app: note-go
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: note-go
        image: cvkiran4/note-app-note-go:21
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/ready
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20

        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: password
        # Constructs the URI for: client, err = mongo.Connect(..., os.Getenv("MONGO_URI"))
        - name: MONGO_URI
          value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@mongo-service:27017/notesdb?authSource=admin"

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: central-auth-secrets
              key: JWT_SECRET